[package]
name = "bbcmd"
version = "0.1.0"
authors = ["Edward Hennessy <ehennes@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
